# Generated by Django 4.2.3 on 2023-12-29 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=256)),
                ("description", models.TextField(max_length=256)),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 12, 29, 17, 13, 39, 665674),
                    ),
                ),
            ],
        ),
    ]
