# Generated by Django 4.2.3 on 2024-01-01 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_article_created_date_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 1, 17, 34, 9, 577842)
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 1, 17, 34, 9, 577842)
            ),
        ),
    ]
