# Generated by Django 4.2.3 on 2024-01-02 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_comment_created_date_alter_article_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="article_description",
            field=models.ManyToManyField(to="main.article"),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 2, 18, 4, 27, 149745)
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 2, 18, 4, 27, 149745)
            ),
        ),
    ]
