# Generated by Django 4.2.3 on 2024-01-02 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_comment_article_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="article_description",),
        migrations.AlterField(
            model_name="article",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 2, 18, 19, 29, 923163)
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 2, 18, 19, 29, 923163)
            ),
        ),
    ]
